backend/snap/employees/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from rest_framework.urls import app_name

from .views import *

app_name='employee'

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path('signup_single/', RegisterSingleView.as_view(), name='register_single'),
    path('signup_hospital/', RegisterHospitalView.as_view(), name='register_hospital')

]

backend/snap/main/urls.py
from django.urls import path

from . import views
from .views import index

app_name='main'

urlpatterns = [
    path('', views.index, name='index'),
]

backend/snap/snap/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(
        'admin/',
        admin.site.urls
    ),

    path(
        '',
        include(
            'main.urls',
        )
    ),

    path(
        'snap/employees/',
        include(
            'employees.urls',
            namespace='employees'
        )
    ),

    path(
        'snap/customers/',
        include(
            'customer.urls',
            namespace='customers'
        )
    )
]

backend/snap/main/models.py
from django.db import models

# Create your models here.

backend/snap/main/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context={
        'title': 'SnapMed'
    }
    return render(request, 'index.html', context=context)

backend/snap/main/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
    <h1>Welcome to MedSnap</h1>
    {%  if user.is_authenticated %}
        <h1>{{ user }}</h1>
        <h3><a href="{% url 'employee:logout' %}">Employee Logout</a></h3>
    {% else %}
    <h1><a href="{% url 'employee:login' %}">Login</a></h1>
    <h1><a href="{% url 'employee:register_single' %}">SignUp single</a></h1>
    <h1><a href="{% url 'employee:register_hospital' %}">SignUp Hospital</a></h1>
    {% endif %}
</body>
</html>